name: Deploy

on:
  # Trigger the workflow on push on main branch,
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.8"
      - uses: Gr1N/setup-poetry@v8
      - run: poetry export -f requirements.txt --without-hashes -o requirements.txt
      - run: poetry config virtualenvs.create false && poetry install --no-interaction
      - name: GitHub Pelican Build Action
        uses: iranzo/gh-pages-pelican-action@1.0.3
