name: Deploy

on:
  # Trigger the workflow on push on main branch,
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.8"
      - uses: Gr1N/setup-poetry@v8
      - run: poetry export -f requirements.txt --without-hashes -o requirements.txt
      - run: poetry install --no-interaction
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build
        run: poetry run pelican content
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
