name: Deploy

on:
  # Trigger the workflow on push on main branch,
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.8"
      - name: Set up poetry
        uses: Gr1N/setup-poetry@v9
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      - name: Build
        run: poetry run pelican content
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: output
          fqdn: studio.kalavera.xyz
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
